### PR TITLE
removed lines that hide submission time

### PR DESCRIPTION
**Pull request by mobyte0**
I'm not really sure why this was implemented in the first place. It just seems like an inconvenience without any real benefit to me.

### CODE REVIEW

**Comment by EthanChrisp** [comment]
Could I get a screenshot of the element that was hidden because of this? Not sure exactly what this is or why it was there either.

**Comment by mobyte0** [comment]
http://i.imgur.com/Ihz8tll.png

**Comment by Foggalong** [comment]
It looks like the element was initially hidden in d96afa3d98fb94c00b96056e8a1eabf0fc36b315 which was a big commit by @Axel-- for the 4.0 release so there's no reference I can find for why it was done in the commit or issues.

**Comment by EthanChrisp** [comment]
Odd, I agree this shouldn't have been hidden. Will merge.

Thanks!

**Pull request merged**
