### PR TITLE
Grey out and disable archived post voting arrows (#125)

### PR DESCRIPTION
**Pull request by Zmodem-**
Will gray out and remove voting rights on archived posts, and all subsequent comment voting arrows.

Note: There are a few other residual fixes in place here as well (from the last pull/commit).

### CODE REVIEW

**Comment by EthanChrisp** [comment]
Thanks, will get this added in the next commit.

**Comment by Zmodem-** [comment]
I'm completely ashamed to admit this, but I did not realize I was receiving comments on my commits :o lol Goodness, I'm so sorry and apologize that I haven't noticed these before! I'm glad that I've been helping in some small way lol.

**Comment by EthanChrisp** [comment]
No worries! I added a CONTRIBUTING guidelines document for Pull Requests, be sure to read over that and feel free to submit anymore PRs 😄

**Comment by Zmodem-** [comment]
Thanks! Jumping on that ASAP :D

**Pull request closed without merging**
